POST http://localhost:3000/books
Content-Type: application/json

# book1
# {
#     "title": "Rich Dad Poor Dad",
#     "author":"Robert Kiyosaki"
# }

# book2
# {
#     "title": "The Chord Chemistry",
#     "author":"Tedd Greene"
# }


# book3
{
    "title": "Blues All Around Me",
    "author":"B B King"
}

POST http://localhost:3000/students
Content-Type: application/json

# student 1
{
  "student_name": "Gautam Chandra Saha",
  "reg_no": "201900099",
  "hobby": "sleeping"
}


# student 2
{
  "student_name": "abcd",
  "reg_no": "2019abcd",
  "hobby": "abcd"
}


# student 3
{
  "student_name": "efgh",
  "reg_no": "2019efgh",
  "hobby": "efgh"
}